name: MobDisguisePVPControl
main: pgDev.bukkit.MDPVPControl.MDPVPCMain
version: 0.3
author: PG Dev Team
authors: [Devil Boy]
description: You'll know who hurt you.
softdepend: [MobDisguise, DisguiseCraft]

permissions:
    mdpvpcontrol.nodamagedisguiseloss:
        default: op
        description: Does not lose disguise upon being damaged.
    mdpvpcontrol.candisguiseattack:
        default: op
        description: Can attack others while disguised.
    mdpvpcontrol.hidedisguisedeath:
        default: op
        description: Will not show a death message if killed while disguised.